- StartNg/README.md
- search.html
https://ore-cathy.github.io/Search-page/
> Search Page

- curriculum.html
Fixed the accordion and now the plus button shows at default and changes to minus when clicked and also fixed the font-family and also other minor fixes.
here is the link to the hosted site - https://boluwatife2904.github.io/index.html
> Fixed Accordion and other minor bugs

- termsOfService.html
https://tana00.github.io/StartNg/termsOfService.html
> Update termsOfService.html on mobile

- about.html
- blog1.html
- blog2.html
- contactus.html
- curriculum.html
- faq.html
- index.html
- individual_course.html
- register.html
- search.html
- termsOfService.html
I added the correct paths to links in the pages in Development branch. Pls merge this PR
> I ensured that all links in the pages are working

- search.html
Implemented search functionality for the search page
https://papa28x4.github.io/StartNg/search.html
> Search Functionality for the search page

- README.md
- about.html
- blog1.html
- blog2.html
- complete.html
- contactus.html
- courses.html
- curriculum.html
- fullstack.html
- hireGrad.html
- index.html
- javascript-course.html
- laravel.html
- register.html
- search.html
- ui-ux.html
> Revert "Frontend"

- register.html
Register.html footer social icons not displaying. Fix.
every form should be validated
Add JavaScript validation to the form.
In the mobile view of this page, there is no space between input form fields"
https://gthankgod.github.io/StartNg/register.html
> Register Page Fixes

- courses.html
- search.html
Separated the courses on the courses.html file to give space on mobile.
> aligned courses

- curriculum.html
Replaced some images with actual code and fixed alignment of some elements
> Made required changes to curriculum.html

- about.html
- blog1.html
- blog2.html
- complete.html
- contactus.html
- courses.html
- curriculum.html
- footer/footer.html
- fullstack.html
- help.html
- hireGrad.html
- index.html
- javascript-course.html
- laravel.html
- register.html
- search.html
- termsOfService.html
- ui-ux.html
Enable the start button at the footer of all the pages to lead to register page. Make necessary adjustment  on some pages footer that are not align with the rest.
> Footer - Start button

- laravel.html
Changed images to actual content on the laravel page. 
Test link: https://peaceful-meitner-77236a.netlify.com/
> changed images on laravel course page to actual content

- ui-ux.html
Transformed all the images to plain code
Test link here -> https://joshuafolorunsho.github.io/UI-UX-course-page/ui-ux.html
> UI-UX PAGE (Transformed all the images into code)

- register.html
FE - team 2
https://gthankgod.github.io/StartNg/register.html
Made corrections observed by @Seunfunmi - PM and updated the page...
> Updated Register.html page

- curriculum.html
- search.html
Test link
https://colossalboss.github.io/startng-curriculum/
> Fine tuned curriculum.html

- Profile.html
add profile page as part of admin pages
> add profile page as part of admin pages

- termsofservice.html
The footer updated.
See it here:
https://muideenam.github.io/TermsOfService/termsofservice.html
> https://muideenam.github.io/TermsOfService/termsofservice.html

- ui-ux.html
Before fix
After fix
Test url here -> https://joshuafolorunsho.github.io/UI-UX-course-page/ui-ux.html
> UI-UX Page, fixed margin issues on small screens

- register.html
https://gthankgod.github.io/StartNg/register.html
> Minor fixes to register.html

- javascript-course.html
worked on the feedback from the tester javascript-course.html page
Centralized some sections on small screen and made it responsive
hosted link : https://raw.githack.com/ZennyAOL/StartNg/master/javascript-course.html
> worked on the feedback from the tester javascript-course.html page

- contactus.html
Test url: https://faruq2.github.io/StartNg/contactus.html
> Contactus.html - fixed buttons

- FE/contactus.html
Test url: https://faruq2.github.io/StartNg/contactus.html
> restored fixes for contactus.html

- FE/register.html
Test link: https://gthankgod.github.io/StartNg/register.html
> HTML, and JS validations

- FE/complete.html
Hosted Link to Page - https://hardcore-hermann-0fdee9.netlify.com
> updated complete.html page with content & mild css changes

- resources/views/frontend/frontend/laravel.html
On the laravel page, i added media queries to remove the image on smaller screen devices and center the text content for proper use of the available space.
> removes image on smaller display and centers the text content

- register.html
Add html and Js validations for the registration form.. 
Test link: https://thea10.github.io/register.html
> Add HTML and JS validation for the form

- forgetpassword.html
forget password page
test url : https://ubongndoh.github.io/FAQ/forgetpassword.html
> forget password page

- hireGrad.html
Replace the dummy content with real content, add validation to the form.
Test Link: https://raw.githack.com/cre8tcodes/StartNg/frontend/hireGrad.html
> Update Hireagrad Page

- laravel1Detail.html
This is the page that pops up when the more details on the laravel one course is clicked.
Test Link - https://josh4324.github.io/LaravelOne/
> Laravel One More Details Page

- FE/user-detail.html
Here's the hosted link for the user-detail.html & Table design
> user-detail.html page

- index.html
> Updated the index file

- courses.html
Added lazy load for images
Test URL
https://hngincrediblethor.000webhostapp.com/courses.html
> Added lazy load functionality

- laravel1Detail.html
- laravel2Detail.html
- laravel4Detail.html
Test Link - https://josh4324.github.io/Laravel-Four/.
> Laravel Four more details page

- laravel1Detail.html
- laravel2Detail.html
Updated version of laravel one more detail page
Laravel one more detail page, the page that comes up when you click on the more details under the laravel one course.
it also includes a less and more button in the curriculum section at mobile view and responsive.
Test Link - https://josh4324.github.io/LaravelOne/
> Updated Laravel One more detail page

- laravel1Detail.html
- laravel2Detail.html
- laravel3Detail.html
Test Link - https://josh4324.github.io/Lavarel-Three/.
> Laravel Three more details page

- login.html
Implement error message for failed sign in on sign in page
> Error Message

- fullstack.html
Adding content and changing some responsiveness.
https://miz-kas.github.io/indivicourse/
> Adding Fullstack.html

- login.html
Link forgetpassword.html to the login page please kindly merge it thanks
> forgetpassword.html link

- FE/laravel.html
**Task on laravel.html has been fixed & delivered.**
> _changed the content of my page from Lorem to actual content relevant to Laravel, made sure it's responsive on mobile and web, fixed the alignment of the karaoke course page, and resolved issues with padding and margin_
**Hosted Link** - https://practical-hypatia-81c9b8.netlify.com/
(PS: Background color for sections after call-to-action has been fixed. Please see screenshot)
**Screenshot** -
> laravel.html

- laravel2Detail.html
- python1detail.html
Python one Course Detail Page
Python one more detail page, the page that comes up when you click on the more details under the python one course.
it also includes a less and more button in the curriculum section at mobile view and responsive.
Test Link - https://josh4324.github.io/PythonOne/
> Josh python one

- laravel2Detail.html
- laraveldetail.html
- python1detail.html
Laravel detail page, the page that comes up when you click on the  more details under the laravel course.
it also includes a less and more button in the curriculum section at mobile view.
Test Link - https://josh4324.github.io/laravel/
> Laravel Detail Page

- css/view-course.css
- dashboard.html
- view-course.html
> view course

- termsOfService.html
- termsofservice.html
> termsofservice.html

- forgetpassword.html
- new-password.html
- successful.html
new password page and password reset successful page
> new password page and password reset successful page

- tutor-profile.html
Add Tutor Profile Page 
hosted link : http://www.spendless.byethost7.com/?i=1
> Add Tutor Profile page

- coming-soon.html
[Comin-soon test url](https://lancer-app.000webhostapp.com/startng/coming-soon.html)
> modified coming soon page

- resources/views/pages/curriculum.blade.php
> Revert "Added curriculum contents"
